### ISSUE TITLE
Github actions checkout

### ISSUE THREAD

**Issue by Carbon225** [namehash/nameguard#178]
We checkout like this:

```
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
```

Should we use `ref`? It makes the action run on the code before the merge, not after.
I think it would be better to run on the merged version.
This should avoid situations where the PR passes and main fails.

@djstrong ?

**Comment by djstrong** [comment]
Good catch! https://github.com/namehash/nameguard/pull/180
